### ISSUE TITLE
报错CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by huangjf11** [shaoyuyoung/CT5#1]
运行时modeling_t5 .py报错

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be 
incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

请问这个代码初始可以跑吗

**Comment by shaoyuyoung** [comment]
我很抱歉，但是这个代码仓库中似乎并没有这个modeling_t5 .py这个文件。发生此类错误的原因可能是你的环境配置问题。请检查你的cuda是否正确安装以及你的pytorch是否是gpu版本的。这个代码是可以直接在我的电脑上运行的
